version: '3'
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - '80:800'
      - '443:443'

  openproject:
    image: 'openproject/community'
    volumes:
      - /var/lib/openproject/pgdata:/var/lib/postgresql/9.6/main
      - /var/lib/openproject/logs:/var/log/supervisor
      - /var/lib/openproject/static:/var/db/openproject
    
    environment: 
      - SECRET_KEY_BASE=1234asd123asdxaw
      - OPENPROJECT_ATTACHMENTS__STORAGE=fog
      - OPENPROJECT_FOG_CREDENTIALS_AWS__ACCESS__KEY__ID=""
      - OPENPROJECT_FOG_CREDENTIALS_AWS__SECRET__ACCESS__KEY=""
      - OPENPROJECT_FOG_CREDENTIALS_PROVIDER=AWS
      - OPENPROJECT_FOG_CREDENTIALS_REGION="ap-northeast-2"
      - OPENPROJECT_FOG_DIRECTORY=openproject-uploads
      - EMAIL_DELIVERY_METHOD=smtp
      - SMTP_ADDRESS=smtp.sendgrid.net
      - SMTP_PORT=587
      - SMTP_DOMAIN=openproject.blackruby.studio
      - SMTP_AUTHENTICATION=login
      - SMTP_ENABLE_STARTTLS_AUTO=true
      - SMTP_USER_NAME="apikey"
      - SMTP_PASSWORD=