version: "3"
services:
  nginx-ssl-proxy:
    restart: always
    image: danieldent/nginx-ssl-proxy
    environment:
      - UPSTREAM=127.0.0.1:8080
      - SERVERNAME=test.example.com
      - EXTRANAMES=www.test.example.com,test2.example.com
  ports:
    - "80:800"
    - "443:443"
  volumes:
    - "/etc/letsencrypt"

  openproject:
    image: "openproject/community"
    volumes:
      - /var/lib/openproject/pgdata:/var/lib/postgresql/9.6/main
      - /var/lib/openproject/logs:/var/log/supervisor
      - /var/lib/openproject/static:/var/db/openproject

    environment:
      - SECRET_KEY_BASE=bl@ckrubyStudioSecret2134
      - OPENPROJECT_ATTACHMENTS__STORAGE=fog
      - OPENPROJECT_FOG_CREDENTIALS_AWS__ACCESS__KEY__ID=""
      - OPENPROJECT_FOG_CREDENTIALS_AWS__SECRET__ACCESS__KEY=""
      - OPENPROJECT_FOG_CREDENTIALS_PROVIDER=AWS
      - OPENPROJECT_FOG_CREDENTIALS_REGION="ap-northeast-2"
      - OPENPROJECT_FOG_DIRECTORY=openproject-uploads
